version: 1.0.0
sources:
- name: item_id
  source: Item
  dtype: int
  default_val: '0'
- name: item_type
  source: Item
  dtype: string
  default_val: unknown
- name: title
  source: Item
  dtype: string
  default_val: ''
- name: content
  source: Item
  dtype: string
  default_val: ''
- name: insight
  source: Item
  dtype: string
  default_val: ''
- name: roleneeds_first_label
  source: Item
  dtype: string
  default_val: '[]'
- name: roleneeds_second_label
  source: Item
  dtype: string
  default_val: '[]'
- name: invest_label
  source: Item
  dtype: string
  default_val: '[]'
- name: invest_label_second
  source: Item
  dtype: string
  default_val: '[]'
- name: invest_label_third
  source: Item
  dtype: string
  default_val: '[]'
- name: quality_score_label
  source: Item
  dtype: float
  default_val: '0.0'
- name: stock_list
  source: Item
  dtype: string
  default_val: '[]'
- name: entity_words_label
  source: Item
  dtype: string
  default_val: '[]'
- name: item_entities_v3
  source: Item
  dtype: string
  default_val: '[]'
- name: author_id
  source: Item
  dtype: int
  default_val: '0'
- name: author
  source: Item
  dtype: string
  default_val: ''
- name: source_name
  source: Item
  dtype: string
  default_val: unknown
- name: emb_id
  source: Item
  dtype: string
  default_val: '[]'
